services:
  sql-db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - internal
    hostname: db
    environment:
      MYSQL_DATABASE: arch
      MYSQL_ROOT_PASSWORD: arch
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:z


  spring-app:
    container_name: api
    build: 
      dockerfile: ./Dockerfile
    pull_policy: build
    ports:
      - "8080:8080"
    depends_on:
      - sql-db
    develop:
      watch:
        - path: ./app 
          action: rebuild
    environment:
      - MYSQL_HOST=sql-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=arch
      - MYSQL_USER=root
      - MYSQL_PASSWORD=arch
      - MYSQL_ROOT_PASSWORD=arch
    networks:
      - internal
volumes:
  db_data:


networks:
  internal:
    driver: bridge

